version: "3.8"
services:
  app:
    volumes:
      - .:/app
    restart: unless-stopped
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dbname
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  redis:
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10
